PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE USER( USER_ID TEXT PRIMARY KEY, NAME TEXT NOT NULL, EMAIL_ID TEXT NOT NULL, GENDER TEXT NOT NULL, AGE INT NOT NULL, FOREIGN KEY(EMAIL_ID) REFERENCES CREDENTIALS(EMAIL_ID));
CREATE TABLE CREDENTIALS( EMAIL_ID TEXT PRIMARY KEY, PASSWORD TEXT NOT NULL);
CREATE TABLE PRODUCT( PRODUCT_ID INT PRIMARY KEY, NAME TEXT NOT NULL, CATEGORY_ID INT, PRICE INT);
CREATE TABLE MEAL( MEAL_ID INT, PRODUCT_ID INT, PRIMARY KEY (MEAL_ID, PRODUCT_ID), FOREIGN KEY(MEAL_ID) REFERENCES MEALDETAILS(MEAL_ID), FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));
CREATE table MEALDETAILS( MEAL_ID INT PRIMARY KEY, NAME TEXT NOT NULL, PRICE INT NOT NULL, AVAILABILITY INT NOT NULL);
COMMIT;
