# -*- coding: utf-8 -*-
"""predict_auto_encoder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-O9emBbQ_Ap0x2PmvtAbzP3k26WFmw8
"""

import pandas as pd
import os

Meal_Recommender_path = os.getcwd() + "/app/Meal_Recommender/"

def fetch_pred(pred_df, user_id):
#   print(user_id)
  # all_cust = customer_id_df.loc[0].tolist()
  temp = pd.DataFrame()
  temp = pred_df[pred_df[0] == user_id]

  all_prod = temp.iloc[0,1]

  return all_prod

def predict_auto_encoder(cluster_num, user_id):

    # read the csv for this cluster_num
    # check if it already exists
    csv_path = Meal_Recommender_path + str(cluster_num) + "_ids.csv"

    customer_id_df = pd.read_csv(csv_path,header=None)

    all_cust = customer_id_df.loc[0].tolist()
#     print (all_cust[:-1])
    all_cust = list(map(int, all_cust[:-1]))
    print ("Customers in same cluster as this user ")
    print ("All_Cust: ", all_cust)

    temp = pd.DataFrame()
    # read the predictions for this cluster
    pred_csv_path = Meal_Recommender_path + str(cluster_num) + "_preds.csv"
    pred_df = pd.read_csv(pred_csv_path, header=None)
    temp = []
    if user_id in all_cust:
      # existing user
      # fetch the prediction
      temp = fetch_pred(pred_df, user_id)
    else:
      # a new user has come
      import random
      random_similar_user = random.randint(0,len(pred_df)-1)
      temp = fetch_pred(pred_df, all_cust[random_similar_user])
    temp = temp.replace("[", "")
    temp = temp.replace("]", "")
    temp = temp.split()
    results = list(map(int, temp))
    print ("Reccommended product ids ")
    print (results)
    return results

# a = predict_auto_encoder(1, 8)
